FROM ubuntu:22.04

RUN apt update && apt install -y apache2

# Activar mod_rewrite (permite reescribir y redirigir URLs de forma flexible y potente mediante reglas personalizadas)
RUN a2enmod rewrite

# Apache debe correr en primer plano
CMD ["apachectl", "-D", "FOREGROUND"]

EXPOSE 80
